// Spec section 12 — Contractor Requests. The planning service has no request store yet,
// so this tab shows the contract context it will hang off and the contract it expects.

import { PPILL } from "../data/style";
import { usePlan } from "../state/plan";
import type { TabId } from "../shell/tabs";

export function Requests({ go }: { go: (t: TabId) => void }) {
  const plan = usePlan();

  return (
    <>
      <div style={{ display: "flex", alignItems: "center", gap: 12 }}>
        <div style={{ display: "flex", flexDirection: "column", gap: 2 }}>
          <h1 className="h1">Contractor Requests</h1>
          <span className="muted small">
            Access requests measured against the approved plan · alternatives generated by the what-if engine
          </span>
        </div>
        <div style={{ flex: 1 }} />
        <span className="pill p-grey">Awaiting backend</span>
      </div>

      <div className="callout c-amber" style={{ display: "flex", flexDirection: "column", gap: 8 }}>
        <span style={{ fontWeight: 600 }}>No request store exists yet.</span>
        <span>
          This tab needs <span className="mono">GET /api/requests</span> and{" "}
          <span className="mono">GET /api/requests/&#123;id&#125;/assessment</span>. Everything an assessment needs is
          already computable: a request is a capacity override, so its impact is the same what-if the Scenarios tab
          runs, and the alternatives are the neighbouring weeks where the location has room.
        </span>
        <span className="small muted">
          Until then, use Scenarios to price a request by hand: add an extra access night at the location and week the
          contractor asked for, and read the score delta and the activities that move.
        </span>
        <div>
          <button className="btn btn-sm btn-primary" onClick={() => go("scenarios")}>
            Open Scenarios
          </button>
        </div>
      </div>

      <div className="card" style={{ overflow: "hidden" }}>
        <div style={{ padding: "12px 16px", borderBottom: "1px solid #e6e9ef", display: "flex", alignItems: "center", gap: 10 }}>
          <span className="h2">Who could raise one</span>
          <div style={{ flex: 1 }} />
          <span className="small muted">
            {plan.contracts.length} contracts in {plan.name} · weekly caps and workfronts from the demand book
          </span>
        </div>
        <table className="tbl">
          <thead>
            <tr>
              <th>Contract</th>
              <th>Name</th>
              <th>Priority</th>
              <th>Access type</th>
              <th>Weekly cap</th>
              <th>Workfronts</th>
              <th>Slack</th>
              <th>Status</th>
            </tr>
          </thead>
          <tbody>
            {plan.contracts.map((c) => (
              <tr key={c.id}>
                <td className="mono" style={{ fontWeight: 600 }}>
                  {c.id}
                </td>
                <td>{c.name}</td>
                <td>
                  <span className={PPILL[c.priority]}>P{c.priority}</span>
                </td>
                <td>{c.accessType}</td>
                <td>{c.weeklyCap} nights</td>
                <td>{c.workfronts}</td>
                <td>
                  <span className={c.slack < 0 ? "pill p-crit" : c.slack === 0 ? "pill p-warn" : "pill p-ok"}>
                    {c.slack < 0 ? `${c.slack} wk` : c.slack === 0 ? "0 wk" : `+${c.slack} wk`}
                  </span>
                </td>
                <td className="muted">{c.status}</td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>
    </>
  );
}
